# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shawn Hoffman
email: shawn.p.hoffman@gmail.com
description: > # Official website for Shawn P Hoffman, Bay-Area Software Engineer & Problem Solver.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shawnphoffman.com" # the base hostname & protocol for your site
# twitter_username: trap
github_username:  shawnphoffman

# Build settings
markdown: kramdown
