const nationalParks: string[] = [
	'Acadia National Park',
	// 'Arches National Park',
	// 'Badlands National Park',
	// 'Big Bend National Park',
	// 'Biscayne National Park',
	// 'Black Canyon Of The Gunnison National Park',
	'Bryce Canyon National Park',
	// 'Canyonlands National Park',
	// 'Capitol Reef National Park',
	// 'Carlsbad Caverns National Park',
	// 'Channel Islands National Park',
	// 'Congaree National Park',
	'Crater Lake National Park',
	// 'Cuyahoga Valley National Park',
	'Death Valley National Park',
	// 'Denali National Park & Preserve',
	'Dry Tortugas National Park',
	'Everglades National Park',
	// 'Gates Of The Arctic National Park & Preserve',
	// 'Gettysburg National Military Park',
	// 'Glacier Bay National Park & Preserve',
	// 'Glacier National Park',
	'Grand Canyon National Park',
	// 'Grand Teton National Park',
	// 'Great Basin National Park',
	// 'Great Sand Dunes National Park & Preserve',
	'Great Smoky Mountains National Park',
	// 'Guadalupe Mountains National Park',
	// 'Haleakala National Park',
	// 'Harpers Ferry National Historical Park',
	// 'Hawaii Volcanoes National Park',
	// 'Hot Springs National Park',
	// 'Isle Royale National Park',
	// 'Joshua Tree National Park',
	// 'Katmai National Park & Preserve',
	// 'Kenai Fjords National Park',
	// 'Kings Canyon National Park',
	// 'Kobuk Valley National Park',
	// 'Lake Clark National Park & Preserve',
	'Lassen Volcanic National Park',
	'Mammoth Cave National Park',
	// 'Mesa Verde National Park',
	// 'Mount Rainier National Park',
	// 'National Park of American Samoa',
	// 'North Cascades National Park',
	// 'Olympic National Park',
	'Petrified Forest National Park',
	// 'Pinnacles National Park',
	'Redwood National and State Parks',
	'Rocky Mountain National Park',
	// 'Saguaro National Park',
	'Sequoia & Kings Canyon National Parks',
	// 'Shenandoah National Park',
	// 'Theodore Roosevelt National Park',
	// 'Valley Forge National Historical Park',
	// 'Virgin Islands National Park',
	// 'Voyageurs National Park',
	// 'Wind Cave National Park',
	// 'Wolf Trap National Park for the Performing Arts',
	// 'Wrangell - St Elias National Park & Preserve',
	// 'Yellowstone National Park',
	'Yosemite National Park',
	// 'Zion National Park',
]

export default nationalParks

/*
'Abraham Lincoln Birthplace National Historical Park',
'Acadia National Park',
'Adams National Historical Park',
'African Burial Ground National Monument',
'Agate Fossil Beds National Monument',
'Alagnak Wild River',
'Alibates Flint Quarries National Monument',
'Allegheny Portage Railroad National Historic Site',
'American Memorial Park',
'Amistad National Recreation Area',
'Anacostia Park',
'Andersonville National Historic Site',
'Andrew Johnson National Historic Site',
'Aniakchak National Monument & Preserve',
'Antietam National Battlefield',
'Apostle Islands National Lakeshore',
'Appalachian National Scenic Trail',
'Appomattox Court House National Historical Park',
'Arches National Park',
'Arkansas Post National Memorial',
'Arlington House, The Robert  E. Lee Memorial',
'Assateague Island National Seashore',
'Aztec Ruins National Monument',
'Badlands National Park',
'Baltimore-Washington Parkway',
'Bandelier National Monument',
'Bent's Old Fort National Historic Site',
'Bering Land Bridge National Preserve',
'Big Bend National Park',
'Big Cypress National Preserve',
'Big Hole National Battlefield',
'Big South Fork National River & Recreation Area',
'Big Thicket National Preserve',
'Bighorn Canyon National Recreation Area',
'Biscayne National Park',
'Black Canyon Of The Gunnison National Park',
'Blue Ridge Parkway',
'Bluestone National Scenic River',
'Booker T Washington National Monument',
'Boston African American National Historic Site',
'Boston Harbor Islands National Recreation Area',
'Boston National Historical Park',
'Brices Cross Roads National Battlefield Site',
'Brown v. Board Of Education National Historic Site',
'Bryce Canyon National Park',
'Buck Island Reef National Monument',
'Buffalo National River',
'Cabrillo National Monument',
'Canaveral National Seashore',
'Cane River Creole National Historical Park',
'Canyon De Chelly National Monument',
'Canyonlands National Park',
'Cape Cod National Seashore',
'Cape Hatteras National Seashore',
'Cape Krusenstern National Monument',
'Cape Lookout National Seashore',
'Capitol Reef National Park',
'Capulin Volcano National Monument',
'Carl Sandburg Home National Historic Site',
'Carlsbad Caverns National Park',
'Carter G. Woodson Home National Historic Site',
'Casa Grande Ruins National Monument',
'Castillo De San Marcos National Monument',
'Castle Clinton National Monument',
'Catoctin Mountain Park',
'Cedar Breaks National Monument',
'Cedar Creek & Belle Grove National Historical Park',
'Central High School National Historic Site',
'Chaco Culture National Historical Park',
'Chamizal National Memorial',
'Channel Islands National Park',
'Charles Pinckney National Historic Site',
'Chattahoochee River National Recreation Area',
'Chesapeake & Ohio Canal National Historical Park',
'Chickamauga & Chattanooga National Military Park',
'Chickasaw National Recreation Area',
'Chiricahua National Monument',
'Christiansted National Historic Site',
'City Of Rocks National Reserve',
'Clara Barton National Historic Site',
'Colonial National Historical Park',
'Colorado National Monument',
'Congaree National Park',
'Constitution Gardens',
'Coronado National Memorial',
'Cowpens National Battlefield',
'Crater Lake National Park',
'Craters Of The Moon National Monument & Preserve',
'Cumberland Gap National Historical Park',
'Cumberland Island National Seashore',
'Curecanti National Recreation Area',
'Cuyahoga Valley National Park',
'Dayton Aviation Heritage National Historical Park',
'De Soto National Memorial',
'Death Valley National Park',
'Delaware Water Gap National Recreation Area',
'Denali National Park & Preserve',
'Devils Postpile National Monument',
'Devils Tower National Monument',
'Dinosaur National Monument',
'Dry Tortugas National Park',
'Ebey's Landing National Historical Reserve',
'Edgar Allan Poe National Historic Site',
'Effigy Mounds National Monument',
'Eisenhower National Historic Site',
'El Malpais National Monument',
'El Morro National Monument',
'Eleanor Roosevelt National Historic Site',
'Eugene O'Neill National Historic Site',
'Everglades National Park',
'Federal Hall National Memorial',
'Fire Island National Seashore',
'First Ladies National Historic Site',
'Flight 93 National Memorial',
'Florissant Fossil Beds National Monument',
'Ford's Theatre National Historic Site',
'Fort Bowie National Historic Site',
'Fort Caroline National Memorial',
'Fort Davis National Historic Site',
'Fort Donelson National Battlefield',
'Fort Dupont Park',
'Fort Foote Park',
'Fort Frederica National Monument',
'Fort Laramie National Historic Site',
'Fort Larned National Historic Site',
'Fort Matanzas National Monument',
'Fort McHenry National Monument and Historic Shrine',
'Fort Necessity National Battlefield',
'Fort Point National Historic Site',
'Fort Pulaski National Monument',
'Fort Raleigh National Historic Site',
'Fort Scott National Historic Site',
'Fort Smith National Historic Site',
'Fort Stanwix National Monument',
'Fort Sumter National Monument',
'Fort Union National Monument',
'Fort Union Trading Post National Historic Site',
'Fort Vancouver National Historic Site',
'Fort Washington Park',
'Fossil Butte National Monument',
'Franklin Delano Roosevelt Memorial',
'Frederick Douglass National Historic Site',
'Frederick Law Olmsted National Historic Site',
'Fredericksburg & Spotsylvania National Military Park',
'Friendship Hill National Historic Site',
'Gates Of The Arctic National Park & Preserve',
'Gateway National Recreation Area',
'Gauley River National Recreation Area',
'General Grant National Memorial',
'George Rogers Clark National Historical Park',
'George Washington Birthplace National Monument',
'George Washington Carver National Monument',
'George Washington Memorial Parkway',
'Gettysburg National Military Park',
'Gila Cliff Dwellings National Monument',
'Glacier Bay National Park & Preserve',
'Glacier National Park',
'Glen Canyon National Recreation Area',
'Gloria Dei Church National Historic Site',
'Golden Gate National Recreation Area',
'Golden Spike National Historic Site',
'Governors Island National Monument',
'Grand Canyon National Park',
'Grand Portage National Monument',
'Grand Teton National Park',
'Grant-Kohrs Ranch National Historic Site',
'Great Basin National Park',
'Great Egg Harbor River',
'Great Sand Dunes National Park & Preserve',
'Great Smoky Mountains National Park',
'Green Springs',
'Greenbelt Park',
'Guadalupe Mountains National Park',
'Guilford Courthouse National Military Park',
'Gulf Islands National Seashore',
'Hagerman Fossil Beds National Monument',
'Haleakala National Park',
'Hamilton Grange National Memorial',
'Hampton National Historic Site',
'Harmony Hall',
'Harpers Ferry National Historical Park',
'Harry S Truman National Historic Site',
'Hawaii Volcanoes National Park',
'Herbert Hoover National Historic Site',
'Hohokam Pima National Monument',
'Home Of Franklin D Roosevelt National Historic Site',
'Homestead National Monument of America',
'Hopewell Culture National Historical Park',
'Hopewell Furnace National Historic Site',
'Horseshoe Bend National Military Park',
'Hot Springs National Park',
'Hovenweep National Monument',
'Hubbell Trading Post National Historic Site',
'Ice Age National Scenic Trail',
'Illinois & Michigan Canal National Heritage Corridor',
'Independence National Historical Park',
'Indiana Dunes National Lakeshore',
'Isle Royale National Park',
'James A Garfield National Historic Site',
'Jean Lafitte National Historical Park and Preserve',
'Jefferson National Expansion Memorial',
'Jewel Cave National Monument',
'Jimmy Carter National Historic Site',
'John D Rockefeller Jr Memorial Parkway',
'John Day Fossil Beds National Monument',
'John F Kennedy National Historic Site',
'John Muir National Historic Site',
'Johnstown Flood National Memorial',
'Joshua Tree National Park',
'Kalaupapa National Historical Park',
'Kaloko-Honokohau National Historical Park',
'Katmai National Park & Preserve',
'Kenai Fjords National Park',
'Kenilworth Park & Aquatic Gardens',
'Kennesaw Mountain National Battlefield Park',
'Keweenaw National Historical Park',
'Kings Canyon National Park',
'Kings Mountain National Military Park',
'Klondike Gold Rush National Historical Park',
'Knife River Indian Villages National Historic Site',
'Kobuk Valley National Park',
'Korean War Veterans Memorial',
'Lake Chelan National Recreation Area',
'Lake Clark National Park & Preserve',
'Lake Meredith National Recreation Area',
'Lake Roosevelt National Recreation Area',
'Lassen Volcanic National Park',
'Lava Beds National Monument',
'Lewis & Clark National Historic Trail',
'Lewis and Clark National Historical Park',
'Lincoln Boyhood National Memorial',
'Lincoln Home National Historic Site',
'Lincoln Memorial',
'Little Bighorn Battlefield National Monument',
'Little River Canyon National Preserve',
'Longfellow House - Washington's Headquarters National Historic Site',
'Lowell National Historical Park',
'Lyndon B Johnson National Historical Park',
'Lyndon Baines Johnson Memorial Grove on the Potomac',
'Maggie L Walker National Historic Site',
'Mammoth Cave National Park',
'Manassas National Battlefield Park',
'Manzanar National Historic Site',
'Marsh - Billings - Rockefeller National Historical Park',
'Martin Luther King Jr National Historic Site',
'Martin Van Buren National Historic Site',
'Mary McLeod Bethune Council House National Historic Site',
'Meridian Hill Park',
'Mesa Verde National Park',
'Minidoka National Historic Site',
'Minute Man National Historical Park',
'Minuteman Missile National Historic Site',
'Mississippi National River & Recreation Area',
'Missouri National Recreational River',
'Mojave National Preserve',
'Monocacy National Battlefield',
'Montezuma Castle National Monument',
'Moores Creek National Battlefield',
'Morristown National Historical Park',
'Mount Rainier National Park',
'Mount Rushmore National Memorial',
'Muir Woods National Monument',
'Natchez National Historical Park',
'Natchez Trace Parkway',
'National Capital Parks-East',
'National Mall',
'National Park of American Samoa',
'National World War II Memorial',
'Natural Bridges National Monument',
'Navajo National Monument',
'New Bedford Whaling National Historical Park',
'New Orleans Jazz National Historical Park',
'New River Gorge National River',
'Nez Perce National Historical Park',
'Nicodemus National Historic Site',
'Ninety Six National Historic Site',
'Niobrara National Scenic River',
'Noatak National Preserve',
'North Cascades National Park',
'Obed Wild & Scenic River',
'Ocmulgee National Monument',
'Olympic National Park',
'Oregon Caves National Monument',
'Organ Pipe Cactus National Monument',
'Oxon Cove Park & Oxon Hill Farm',
'Ozark National Scenic Riverways',
'Padre Island National Seashore',
'Palo Alto Battlefield National Historical Park',
'Pea Ridge National Military Park',
'Pecos National Historical Park',
'Pennsylvania Avenue National Historic Site',
'Perry's Victory & International Peace Memorial',
'Petersburg National Battlefield',
'Petrified Forest National Park',
'Petroglyph National Monument',
'Pictured Rocks National Lakeshore',
'Pinnacles National Park',
'Pipe Spring National Monument',
'Pipestone National Monument',
'Piscataway Park',
'Point Reyes National Seashore',
'Port Chicago Naval Magazine National Memorial',
'Potomac Heritage National Scenic Trail',
'Poverty Point National Monument',
'President's Park (White House)',
'Presidio of San Francisco',
'Prince William Forest Park',
'Pu`uhonua O Honaunau National Historical Park',
'Puukohola Heiau National Historic Site',
'Rainbow Bridge National Monument',
'Redwood National and State Parks',
'Richmond National Battlefield Park',
'Rio Grande Wild & Scenic River',
'Rock Creek Park',
'Rocky Mountain National Park',
'Roger Williams National Memorial',
'Rosie the Riveter WWII Home Front National Historical Park',
'Ross Lake National Recreation Area',
'Russell Cave National Monument',
'Sagamore Hill National Historic Site',
'Saguaro National Park',
'Saint Croix Island International Historic Site',
'Saint Croix National Scenic River',
'Saint Paul's Church National Historic Site',
'Saint-Gaudens National Historic Site',
'Salem Maritime National Historic Site',
'Salinas Pueblo Missions National Monument',
'Salt River Bay National Historic Park and Ecological Preserve',
'San Antonio Missions National Historical Park',
'San Francisco Maritime National Historical Park',
'San Juan Island National Historical Park',
'San Juan National Historic Site',
'Sand Creek Massacre National Historic Site',
'Santa Monica Mountains National Recreation Area',
'Saratoga National Historical Park',
'Saugus Iron Works National Historic Site',
'Scotts Bluff National Monument',
'Sequoia & Kings Canyon National Parks',
'Shenandoah National Park',
'Shiloh National Military Park',
'Sitka National Historical Park',
'Sleeping Bear Dunes National Lakeshore',
'Springfield Armory National Historic Site',
'Statue Of Liberty National Monument',
'Steamtown National Historic Site',
'Stones River National Battlefield',
'Sunset Crater Volcano National Monument',
'Tallgrass Prairie National Preserve',
'Thaddeus Kosciuszko National Memorial',
'The Old Stone House',
'Theodore Roosevelt Birthplace National Historic Site',
'Theodore Roosevelt Inaugural National Historic Site',
'Theodore Roosevelt Island Park',
'Theodore Roosevelt National Park',
'Thomas Edison National Historical Park',
'Thomas Jefferson Memorial',
'Thomas Stone National Historic Site',
'Timpanogos Cave National Monument',
'Timucuan Ecological & Historic Preserve',
'Tonto National Monument',
'Tumacacori National Historical Park',
'Tupelo National Battlefield',
'Tuskegee Airmen National Historic Site',
'Tuskegee Institute National Historic Site',
'Tuzigoot National Monument',
'Ulysses S Grant National Historic Site',
'Upper Delaware Scenic & Recreational River',
'Valley Forge National Historical Park',
'Vanderbilt Mansion National Historic Site',
'Vicksburg National Military Park',
'Vietnam Veterans Memorial',
'Virgin Islands Coral Reef National Monument',
'Virgin Islands National Park',
'Voyageurs National Park',
'Walnut Canyon National Monument',
'War In The Pacific National Historical Park',
'Washington Monument',
'Washita Battlefield National Historic Site',
'Weir Farm National Historic Site',
'Whiskeytown National Recreation Area',
'White Sands National Monument',
'Whitman Mission National Historic Site',
'William Howard Taft National Historic Site',
'Wilson's Creek National Battlefield',
'Wind Cave National Park',
'Wolf Trap National Park for the Performing Arts',
'Women's Rights National Historical Park',
'World War II Valor in the Pacific National Monument',
'Wrangell - St Elias National Park & Preserve',
'Wright Brothers National Memorial',
'Wupatki National Monument',
'Yellowstone National Park',
'Yosemite National Park',
'Yucca House National Monument',
'Yukon - Charley Rivers National Preserve',
'Zion National Park',
*/
